#!/usr/bin/env python3
"""Writes THIRD_PARTY_NOTICES.txt from the license files of the sources that
FetchContent downloaded, so the texts match the pinned versions.

Run after a build, and again whenever cmake/versions.cmake changes:
    python tools/make_third_party_notices.py build/windows-release/_deps
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read().strip("\n")


def between(text, start, end=None):
    i = text.index(start)
    j = text.index(end, i) if end else len(text)
    return text[i:j].strip("\n")


def versions():
    text = read(os.path.join(ROOT, "cmake", "versions.cmake"))
    return dict(re.findall(r"set\((\w+) ([^)\s]+)\)", text))


def main():
    deps = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build", "windows-release", "_deps")
    v = versions()
    sfml = os.path.join(deps, "sfml-src")
    headers = os.path.join(sfml, "extlibs", "headers")
    stb = read(os.path.join(headers, "stb_image", "stb_image.h"))
    stb_license = between(stb, "This software is available under 2 licenses", "*/")
    unicodelib = "\n".join(read(os.path.join(headers, "cpp-unicodelib", "unicodelib.h")).splitlines()[:6])
    qoi = "\n".join(read(os.path.join(headers, "qoi", "qoi.h")).splitlines()[:4])
    tinycolormap = between(read(os.path.join(ROOT, "src", "tinycolormap.hpp")), "MIT License", "*/")

    sections = [
        ("SFML " + v["FRACTALS_SFML_GIT_TAG"] + " (zlib License)", read(os.path.join(sfml, "license.md"))),
        ("TGUI " + v["FRACTALS_TGUI_GIT_TAG"] + " (zlib License)", read(os.path.join(deps, "tgui-src", "license.txt"))),
        ("FreeType (FreeType License), built into SFML",
         "Portions of this software are copyright (C) The FreeType Project\n"
         "(https://freetype.org). All rights reserved.\n\n"
         + read(os.path.join(deps, "freetype-src", "docs", "FTL.TXT"))),
        ("HarfBuzz (MIT License), built into SFML", read(os.path.join(deps, "harfbuzz-src", "COPYING"))),
        ("SheenBidi (Apache License 2.0), built into SFML", read(os.path.join(deps, "sheenbidi-src", "LICENSE"))),
        ("stb_image and stb_image_write (MIT License or public domain), in SFML", stb_license),
        ("qoi (MIT License), in SFML", qoi),
        ("cpp-unicodelib (MIT License), in SFML", unicodelib),
        ("glad (generated OpenGL loader), in SFML",
         "SPDX-License-Identifier: (WTFPL OR CC0-1.0) AND Apache-2.0\n"
         "Generated by glad (https://github.com/Dav1dde/glad) from the Khronos API\n"
         "registry, (C) The Khronos Group Inc., Apache License 2.0 (text above, under SheenBidi)."),
        ("nlohmann/json " + v["FRACTALS_JSON_VERSION"] + " (MIT License)", read(os.path.join(deps, "json-src", "LICENSE.MIT"))),
        ("Boost.Multiprecision and Boost.Config " + v["FRACTALS_BOOST_MP_GIT_TAG"] + " (Boost Software License 1.0), deep zoom",
         read(os.path.join(deps, "boost_mp-src", "LICENSE"))),
        ("CMakeRC " + v["FRACTALS_CMRC_GIT_TAG"] + " (MIT License)", read(os.path.join(deps, "cmrc-src", "LICENSE.txt"))),
        ("tinycolormap (MIT License)", tinycolormap),
        ("NVIDIA CUDA runtime " + v["FRACTALS_CUDA_CI_VERSION"],
         "The executable contains the NVIDIA CUDA runtime library (cudart_static) and code\n"
         "compiled from CUDA headers (cuRAND, cuComplex). They are redistributed under the\n"
         "NVIDIA CUDA Toolkit End User License Agreement, which permits redistributing the\n"
         "runtime as part of an application: https://docs.nvidia.com/cuda/eula/\n"
         "Copyright (C) NVIDIA Corporation. All rights reserved."),
    ]

    out = ["THIRD-PARTY NOTICES", "", "fractals includes the following third-party software, linked into the",
           "executable. Their licenses follow.", ""]
    for title, text in sections:
        out += ["=" * 78, title, "=" * 78, "", text, ""]
    path = os.path.join(ROOT, "THIRD_PARTY_NOTICES.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote", path)


if __name__ == "__main__":
    main()
